export const EMIT_SNACKBAR = "EMIT_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export const FETCH_REQS_REQUEST = "FETCH_REQS_REQUEST";
export const FETCH_REQS_SUCCESS = "FETCH_REQS_SUCCESS";
export const FETCH_REQS_FAILURE = "FETCH_REQS_FAILURE";

export const REQUEST_DELETE_REQ = "REQUEST_DELETE_REQ";
export const DELETE_REQ_SUCCESS = "DELETE_REQ_SUCCESS";
export const DELETE_REQ_FAILURE = "DELETE_REQ_FAILURE";

export const REQUEST_SUBMIT_REQ = "REQUEST_SUBMIT_REQ";
export const SUBMIT_REQ_SUCCESS = "SUBMIT_REQ_SUCCESS";
export const SUBMIT_REQ_FAILURE = "SUBMIT_REQ_FAILURE";

export const REQUEST_UPDATE_REQ = "REQUEST_UPDATE_REQ";
export const UPDATE_REQ_SUCCESS = "UPDATE_REQ_SUCCESS";
export const UPDATE_REQ_FAILURE = "UPDATE_REQ_FAILURE";
